# Generated by Django 5.0.7 on 2024-09-04 23:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_subscription_stripe_subscription_id_alter_plan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_image.jpg', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
