# Generated by Django 5.0.7 on 2024-09-20 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_plan_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='upload_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
