# Generated by Django 5.0.7 on 2024-08-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='credited',
            field=models.BooleanField(default=False),
        ),
    ]
