# Generated by Django 5.0.7 on 2024-08-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_withdrawal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='account_number',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='crypto_coin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='crypto_wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('crypto', 'Crypto')], default='paypal', max_length=20),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='paypal_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
