# Generated by Django 5.0.7 on 2024-08-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_withdrawal_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='account_name',
        ),
    ]
